### PR TITLE
add newline to error message

### PR DESCRIPTION
**Pull request by glensc**
the error message lacks trailing newline (`➔` is my shell prompt):

```
➔ ./phpcompatinfo.phar 
Your platform does not statisfy CompatInfo minimum requirements
- Expected PHP extension pdo_sqlite loaded to use SQLite DataBase, is missing➔ 
```

also the spelling error submitted as separate PR as it is in different project:
https://github.com/llaville/php-compatinfo-db/pull/6

altho imho db is wrong package for requirement check function, that code should be in this repository.

### CODE REVIEW

**Comment by llaville** [comment]
The diagnose:run command that is shared betwen php-compatinfo and php-reflect was refactored to use the dependency https://github.com/zendframework/ZendDiagnostics

PHP-Reflect 4.1 (stable) should be released tomorrow

**Comment by remicollet** [comment]
@llaville notice that the LICENSE file is missing in ZendDiagnostics, which make redistribution impossible.

In short, if you distribute it in your phar, you are going to violate BSD license terms.

**Comment by llaville** [comment]
@remicollet Thanks for review (and license missing)

**Comment by llaville** [comment]
Thanks @glensc, but I'll close this issue that won't be fixed, because I've let down `diagnose` command in next version 5.4 that will come shortly now (next week, see ROADMAP #266)

**Comment by glensc** [comment]
@llaville the PR commits in this PR are messed up anyway because somebody **else** did either:
- force pushed base branch (master)
- pushed more commits to **my** branch

I created PR with only with two commits that were authored by me. you can cherry pick them if you wish.

**Comment by glensc** [comment]
also here are comments totally unrelated to my PR, perhaps it's github who messed it up?

**Comment by llaville** [comment]
@glensc No it's me, I've waited too much time to reply to your contribution (sorry for that)

I'm focus now to finish (almost ready) the final version 5.4.0 (as I said that let down some previous features, and monolithic code) and prepare the way to a v6.0 that will simplify CLI (fully drop down PHP Reflect) and refactor console application.

**Pull request closed without merging**
