### PR TITLE
Simplify logic in Reference to make it testable

### PR DESCRIPTION
**Pull request by szepeviktor**
by static analysis

### CODE REVIEW

**Comment by llaville** [comment]
This change is already applied on upcoming v6.0

**Comment by szepeviktor** [comment]
> This change is already applied on upcoming v6.0

Are you sure?

https://github.com/llaville/php-compat-info/blob/952a35d137f02e50ad8fb4fe99f356975f31ca07/src/Bartlett/CompatInfo/Api/Reference.php#L70-L95

**Comment by llaville** [comment]
Not yet published on github repository, but on my local drive.
I've stopped working on v6.0 because php-compatinfo-db v3.0 is my priority before release final version of PHP 8.0

**Comment by szepeviktor** [comment]
> Not yet published on github repository, but on my local drive.

I see! So one has to hack into your computer to take a look at it.

**Pull request closed without merging**
