### PR TITLE
improve GenericTest

### PR DESCRIPTION
**Pull request by remicollet**
Use constantsFromReference dataprovider for testGetConstantsFromReference

The main goal is to avoid having a single test (ex testGetConstantsFromReference) for all value.
With previous mode, this single test on the first failure (making quite difficult to fix reference)

Main problem is that the data provider is run "before" setUpBeforeClass (so $obj not yet defined)

* create class constant "EXTNAME" 
* improved setUpBeforeClass to use new constant and avoid having to overload this method in most case.
* adapt all extension tests
* fix GMP test

With this change, a single run report more issue.

Exexmple, for Http extension
 
     1) Bartlett\Tests\CompatInfo\Reference\Extension\HttpExtensionTest::testGetConstantsFromReference with data set #151 ('http\Url\PARSE_MBLOC', array('http', '2.2.0RC1', '', '5.3.0', '', ''))
     Constant 'http\Url\PARSE_MBLOC', found in Reference, does not exists.
     Failed asserting that false is true.
     
     /work/GIT/php-compat-info/tests/Reference/GenericTest.php:377
     
     2) Bartlett\Tests\CompatInfo\Reference\Extension\HttpExtensionTest::testGetConstantsFromReference with data set #152 ('http\Url\PARSE_MBUTF8', array('http', '2.2.0RC1', '', '5.3.0', '', ''))
     Constant 'http\Url\PARSE_MBUTF8', found in Reference, does not exists.
     Failed asserting that false is true.
     
     /work/GIT/php-compat-info/tests/Reference/GenericTest.php:377
     
     3) Bartlett\Tests\CompatInfo\Reference\Extension\HttpExtensionTest::testGetConstantsFromReference with data set #153 ('http\Url\PARSE_TOIDN', array('http', '2.2.0RC1', '', '5.3.0', '', ''))
     Constant 'http\Url\PARSE_TOIDN', found in Reference, does not exists.
     Failed asserting that false is true.
     
     /work/GIT/php-compat-info/tests/Reference/GenericTest.php:377
     
     4) Bartlett\Tests\CompatInfo\Reference\Extension\HttpExtensionTest::testGetConstantsFromReference with data set #154 ('http\Url\PARSE_TOPCT', array('http', '2.2.0RC1', '', '5.3.0', '', ''))
     Constant 'http\Url\PARSE_TOPCT', found in Reference, does not exists.
     Failed asserting that false is true.
     
     /work/GIT/php-compat-info/tests/Reference/GenericTest.php:377
     
     FAILURES!
     Tests: 166, Assertions: 133, Failures: 4.

### CODE REVIEW

**Comment by remicollet** [comment]
The second commit is tomanage optionalconstant for classconstants and need to be tested (Varnish seems a good test case, with all this optional constant on Windows)

**Comment by llaville** [comment]
I 've deeply reviewed your PR, and I'm sorry to tell you that there is a confusion between standard constant and class constants. 

When dictionnary defined constant with file like  `<extension>.constant.json`, class constants are defined in `<extension>.const.json`. 
Of course you've followed this naming convention, but in `GenericTest` , `testGetConstantsFromReference()` method check only standard constant, and not class constant.

You have a doubt, so have a look with `date` extension and this script 

    <?php

    use Bartlett\CompatInfo\Reference\ExtensionFactory;

    $name = 'date';
    $obj = new ExtensionFactory($name);

    $dict = $obj->getConstants();
    echo 'constants: ' . print_r ($dict);

    $dict = $obj->getClassConstants();
    echo 'class constants: ' . print_r ($dict);

**Comment by remicollet** [comment]
I don't understand what you think is wrong.

Change in testGetConstantsFromReference()
* drop $dict = self::$obj->getConstants();
* drop foreach
* add a @dataprovider constantsFromReference which call $obj->getConstants();

Nothing related to class constants (except the check for $optionalconstants)

And of course this is just to show the idea,
@dataprovider need to be added to other test.

**Comment by llaville** [comment]
Don't misunderstood, what I said, your concept with dataprovider seems good, but it will not check for class constants.
And your commit https://github.com/remicollet/php-compat-info/commit/f022591d76427e644e5149f8620b1edcc7303f8d will do nothing, because it referenced standard constant and not class constant

**Comment by llaville** [comment]
I think we should improve the GenericTest but after the stable release 4.0.0
After all, it will not be the last one. 

Focus to stabilize current copy is more important !

**Comment by remicollet** [comment]
> but it will not check for class constants.

This is not my goal there

**Comment by remicollet** [comment]
> I think we should improve the GenericTest but after the stable release 4.0.0

Do as you want. But don't expect me to rebase when brach will diverge...

**Comment by remicollet** [comment]
Notice: testGetIniEntriesFromReference and testGetConstantsFromReference need CS (remove indentation). Not done for patch legibility

**Comment by llaville** [comment]
Remi,
You're right on idea to improve the GenericTest, but I've another implementation in mind I'll publish soon now. Just to let me finish, polish code, and test with all extensions.

Here are a preview with AMQP extension of what it could render in debug mode with ini entries only 

    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #0 ('amqp.auto_ack', array('1.0.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #1 ('amqp.connect_timeout', array('1.3.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #2 ('amqp.host', array('0.1.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #3 ('amqp.login', array('0.1.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #4 ('amqp.password', array('0.1.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #5 ('amqp.port', array('0.1.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #6 ('amqp.prefetch_count', array('1.0.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #7 ('amqp.read_timeout', array('1.0.10', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #8 ('amqp.timeout', array('1.0.8', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #9 ('amqp.vhost', array('0.1.0', '', '5.2.0', ''))'.
    .
    Starting test 'Bartlett\Tests\CompatInfo\Reference\Extension\AmqpExtensionTest::testGetIniEntriesFromReference with data set #10 ('amqp.write_timeout', array('1.0.10', '', '5.2.0', ''))'.
    .
It uses a generic phpunit `@dataProvider` for all elements (ini, functions, classes, ... ).
Avoid usage of class constant EXTNAME (because I follow a naming convention  XXXExtensionTest) .
Test case is skipped if extension not loaded (use the `@requires extension XXX` phpunit feature).

**Comment by llaville** [comment]
Remi, I'll close this PR, because the future is initialized on issue #189 (roadmap included).
You are encourage to give me your feedback, tomorrow or later when the source code will be published.
BTW, thanks for your initial work :)

**Pull request closed without merging**
