### PR TITLE
raise PHP minimal version

### PR DESCRIPTION
**Pull request by remicollet**
Consistency with php-reflect

### CODE REVIEW

**Comment by remicollet** [comment]
As a side effects, this mean the package will be unmaintained in EPEL-7 (which still have 5.4), thus will be removed in the future.

**Comment by llaville** [comment]
So a question about fedora versions php with distrib supported.

I have in mind to release a major version 6.0 of php-compatinfo without dependencies to php-reflect but still with php 5.6 supported. Remove support to PHP 5 will be introduced in a full rewrite of php-compatinfo 7.0

In which fedora distrib this two new versions will be ? 
Could you write a resume please ?

**Comment by remicollet** [comment]
Fedora don't have any PHP version  < 7.1

* Fedora 26 and 27 have 7.1
* Fedora 28 will have 7.2

**Comment by llaville** [comment]
Thanks for the link

**Pull request merged**
