### PR TITLE
For upcomming 5.5.24 / 5.6.8 + Bugfix

### PR DESCRIPTION
**Pull request by remicollet**
Notice: rev d2b6710 is a fixed not really related to upcoming PHP version.

(Discovered because I have run test against both php 5.6.7 and 5.6.8RC1)

### CODE REVIEW

**Comment by llaville** [comment]
FYI: stable release 4.0.0 will not support PHP 5.6.8RC1 and PHP 5.5.24RC1

**Comment by remicollet** [comment]
But the 2 commits about "php.excludes" are bug fix.

**Comment by llaville** [comment]
for `php.excludes` transformation from string to array, and be exposed anywhere, there is a better location for fix. I'll push it to repo.

**Comment by llaville** [comment]
See commit https://github.com/llaville/php-compat-info/commit/3a11b3846d8a476235478a24bd8857102e2a9d57 for `php.excludes` string to array transformation in one place.  We could clean-up unit tests that transform on demand (when necessary)

**Comment by llaville** [comment]
And also the fix on regression https://github.com/llaville/php-compat-info/commit/96df7744c9b4f7b78410731b16ed0d3fef4a82fd

**Comment by llaville** [comment]
Just for info, about php.excludes  , see also commit https://github.com/llaville/php-compat-info/commit/8c53ecc3b7bfb9327edd90d38183c038636756ff

**Comment by llaville** [comment]
Remi, your contribs on curl and date are commited with https://github.com/llaville/php-compat-info/commit/2761eb2bb9edd6799b960a407877e1b626e830e1 and https://github.com/llaville/php-compat-info/commit/1241a2c82b3606a9f8c1b5319b5630aedf74390f

**Pull request closed without merging**
